version: "3.9"
services:
  maria:
    container_name: maria_backend
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: maria_pass
      MYSQL_DATABASE: mariadb
      MYSQL_USER: maria_user
      MYSQL_PASSWORD: maria_pass
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    container_name: redis_container
    image: redis:latest
    expose:
      - '6379'
    ports:
      - '6379:6379'
    networks:
      - app-network

  server:
    depends_on:
      - redis
      - maria
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: server
    environment:
      - PORT=5005
      - HOST=0.0.0.0
      - DB_NAME=mariadb
      - DB_USER=maria_user
      - DB_PASSWORD=maria_pass
      - DB_HOST=maria
      - DB_PORT=3306
      - DB_SSL=0
      - JWT_ACCESS_SECRET=uf78ef7berf
      - JWT_REFRESH_SECRET=d87fghdgfh
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '5005:5005'
    expose:
      - '5005'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
