version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo-db
    restart: always
    env_file: '.env.docker'
    ports:
      - '27017:27017'
    networks:
      - app-network

  redis:
    container_name: redis_container
    image: redis:latest
    expose:
      - '6379'
    ports:
      - '6379:6379'
    networks:
      - app-network

  server:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: server
    env_file: '.env'
    ports:
      - '5005:5005'
    expose:
      - '5005'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
