version: "3.9"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysqldb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user_mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password_mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password_mysql'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - app-network

  redis:
    container_name: redis_container
    image: redis:latest
    expose:
      - '6379'
    ports:
      - '6379:6379'
    networks:
      - app-network

  server:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: server
    environment:
      - PORT=5005
      - HOST=0.0.0.0
      - DB_NAME=mysqldb
      - DB_USER=user_mysql
      - DB_PASSWORD=password_mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SSL=0
      - JWT_ACCESS_SECRET=uf78ef7berf
      - JWT_REFRESH_SECRET=d87fghdgfh
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '5005:5005'
    expose:
      - '5005'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
